import Dexie, { Table } from 'dexie';

export interface User {  // Export the User interface so it can be used in other files
  id?: number; // The ID is auto-generated by Dexie
  firstName: string;
  lastName: string;
  age: number;
  gender: string;
  medicalHistory: string;
}

class MedicalFormDB extends Dexie {
  users!: Table<User, number>; // Define the 'users' table, now marked as non-nullable
  
  constructor() {
    super('MedicalFormDB');
    this.version(1).stores({
      users: '++id, firstName, lastName, age, gender, medicalHistory', // IndexedDB schema
    });
  }
}

const db = new MedicalFormDB();
export default db;
